// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeZzPuSYh-qZ8KpEO3utoqgbu8XCAl15I',
    appId: '1:745360660470:web:f1b773eb416715620659d7',
    messagingSenderId: '745360660470',
    projectId: 'loum-epilepsie',
    authDomain: 'loum-epilepsie.firebaseapp.com',
    storageBucket: 'loum-epilepsie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BELz6CbpNxMFQoRbK_PYeEaH8iUL6Xw',
    appId: '1:745360660470:android:4acf4562b2cd3b0c0659d7',
    messagingSenderId: '745360660470',
    projectId: 'loum-epilepsie',
    storageBucket: 'loum-epilepsie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-vI_YGznruBeP-9-jtEeRTdkT9l_ZSWA',
    appId: '1:745360660470:ios:a931aeae147cbb110659d7',
    messagingSenderId: '745360660470',
    projectId: 'loum-epilepsie',
    storageBucket: 'loum-epilepsie.firebasestorage.app',
    iosBundleId: 'com.example.loumEpilepsieMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-vI_YGznruBeP-9-jtEeRTdkT9l_ZSWA',
    appId: '1:745360660470:ios:a931aeae147cbb110659d7',
    messagingSenderId: '745360660470',
    projectId: 'loum-epilepsie',
    storageBucket: 'loum-epilepsie.firebasestorage.app',
    iosBundleId: 'com.example.loumEpilepsieMobile',
  );
}
